title = "Custom Gitleaks config"
[extend]
useDefault = true

[[rules]]
id = "api-key-const"
description = "Detects hardcoded API keys defined as a constant."
regex = '''(?i)const\s+apiKey\s*=\s*["']([A-Za-z0-9\-]{5,})["']'''
keywords = ["apikey", "apiKey"]
