name: React DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # Stage 1: Build
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd my-react-app
          npm install

      - name: Build App
        run: |
          cd my-react-app
          npm run build

      # Stage 2: Test (placeholder)
      - name: Test Placeholder
        run: echo "No tests defined yet."

      # Stage 3: Security (Gitleaks) + Report
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          version: v8.18.4
          args: detect --source . --report-format=json --report-path=gitleaks-report.json --exit-code 1

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      # Stage 4: Deploy Docker
      - name: Build Docker Image
        run: docker build -t my-react-app .

      - name: Run Docker Container
        run: docker run -d -p 3000:80 my-react-app
